apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: gcr.io/qwiklabs-gcp-03-a43e64465552/sample-app:v1.0
        ports:
        - containerPort: 8080
